import { BETA_FEATURE_POLICIES } from './featureGraduationPolicy';

/**
 * Central catalogue for calculated metrics exposed by trip scoring and reports.
 *
 * Entries document the intended interpretation of a metric. Calibration notes
 * explicitly identify approximations until validated against external outcomes.
 */
export const DATA_SOURCE_LABELS = Object.freeze({
  android_activity_recognition: 'Android activity recognition',
  android_usage_access: 'Android Usage Access',
  device_motion_imu: 'Device motion IMU',
  imu_yaw: 'IMU yaw',
  gps: 'GPS route samples',
  gps_altitude: 'GPS altitude',
  gps_events: 'GPS event detection',
  gps_inferred_speed_limit: 'GPS-inferred speed limit',
  gps_proxy: 'GPS diagnostic proxy',
  gps_timestamps: 'GPS timestamps',
  legacy_unverified: 'Legacy unverified evidence',
  obd_bluetooth: 'OBD-II Bluetooth',
  open_meteo_weather: 'Open-Meteo weather',
  osm_speed_limit: 'OpenStreetMap speed limits',
  phone_use_usage_access: 'Android Usage Access',
  speed_limit_osm: 'OpenStreetMap speed limits',
  trip_distance_history: 'Trip distance history',
  trip_scores: 'Trip scores',
  trip_timestamps: 'Trip timestamps',
});

export const METRIC_REGISTRY = Object.freeze({
  duration_seconds: {
    label: 'Duration',
    description: 'Elapsed recorded trip duration.',
    dataSources: ['gps_timestamps'],
    minDistanceKm: 0,
    calibrationNote: 'Direct elapsed-time calculation.',
  },
  distance_km: {
    label: 'Distance',
    description: 'Recorded trip distance after GPS route cleaning.',
    dataSources: ['gps'],
    minDistanceKm: 0,
    calibrationNote: 'Haversine distance after GPS quality filtering.',
  },
  avg_speed_kmh: {
    label: 'Average Speed',
    description: 'Distance divided by elapsed trip duration.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Includes stopped time.',
  },
  avg_running_speed_kmh: {
    label: 'Average Moving Speed',
    description: 'Average speed while the vehicle is moving.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Depends on the configured stopped-speed threshold.',
  },
  max_speed_kmh: {
    label: 'Maximum Speed',
    description: 'Highest accepted vehicle speed sample.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Subject to GPS/OBD sampling and quality filtering.',
  },
  score_overall: {
    label: 'Overall Score Estimate',
    description: 'Approximate weighted blend of safety, smoothness, eco and approach-stop evidence.',
    dataSources: ['gps_events', 'obd_bluetooth', 'speed_limit_osm', 'phone_use_usage_access'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'Weighting is provisional and intended for coaching feedback; not a validated safety outcome.',
  },
  score_safety: {
    label: 'Safety Pattern Estimate',
    description: 'Penalises harsh braking, speeding and selected GPS motion/phone-use evidence.',
    dataSources: ['gps_events', 'obd_bluetooth', 'speed_limit_osm', 'phone_use_usage_access'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'Provisional GPS coaching score; not calibrated to crashes, claims, or safety outcomes.',
  },
  score_smoothness: {
    label: 'GPS Motion Smoothness Estimate',
    description: 'Blends event penalties with GPS acceleration, braking and cornering regularity.',
    dataSources: ['gps', 'obd_bluetooth', 'gps_events'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'GPS-derived motion proxy; not vehicle sensor validation.',
  },
  score_eco: {
    label: 'Eco Score Estimate',
    description: 'Estimates efficient speed stability, cruise behaviour and fuel-band operation.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'Coaching proxy; not measured fuel consumption.',
  },
  intersection_score: {
    label: 'Approach-Stop Estimate',
    description: 'Scores observed low-speed approach and stop behaviour; mapped intersection confirmation is not required.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    minSamples: 1,
    calibrationNote: 'Unavailable until a qualifying stop is observed; does not prove a signed or signalized intersection.',
  },
  distraction_score: {
    label: 'Attention-Pattern Estimate',
    description: 'Combines erratic-speed patterns and confirmed phone-use windows when available.',
    dataSources: ['gps_events', 'phone_use_usage_access'],
    minDistanceKm: 0.5,
    minSamples: 0,
    calibrationNote: 'GPS erratic-speed contribution is a diagnostic proxy; it does not measure driver focus.',
  },
  phone_use_score: {
    label: 'Phone Use Score',
    description: 'Penalises phone-use windows confirmed through Android Usage Access.',
    dataSources: ['phone_use_usage_access'],
    minDistanceKm: 0.5,
    minSamples: 0,
    calibrationNote: 'Available only when platform usage evidence is accessible. permission_required: Android Usage Access.',
    permission_required: 'android_usage_access',
    permissionRequiredNote: 'Android Usage Access is required before this metric can distinguish no phone use from unavailable evidence.',
  },
  stop_start_pattern_score: {
    label: 'Stop-Start Pattern Estimate',
    description: 'Estimates repeated acceleration and braking cycles on qualifying city or highway segments.',
    dataSources: ['gps_events'],
    minDistanceKm: 2,
    minSamples: 0,
    calibrationNote: 'Low-evidence GPS proxy; urban mode activates after 2 km of city-speed evidence, highway mode after 5 km. Does not measure following distance.',
  },
  stop_start_pattern_sample_count: {
    label: 'Stop-Start Pattern Sample Count',
    description: 'Number of stop-start patterns supporting the estimate.',
    dataSources: ['gps_events'],
    minDistanceKm: 2,
    calibrationNote: 'Diagnostic support count.',
  },
  stop_start_pattern_highway_score: {
    label: 'Highway Stop-Start Pattern Estimate',
    description: 'Highway-tuned stop-start score for qualifying highway evidence.',
    dataSources: ['gps_events'],
    minDistanceKm: 5,
    minSamples: 0,
    calibrationNote: 'GPS-only highway proxy; does not measure following distance.',
  },
  stop_start_pattern_urban_score: {
    label: 'Urban Stop-Start Pattern Estimate',
    description: 'City-speed stop-start score for qualifying urban evidence.',
    dataSources: ['gps_events'],
    minDistanceKm: 2,
    minSamples: 0,
    calibrationNote: 'GPS-only urban proxy; does not measure following distance.',
  },
  stop_start_pattern_highway_count: {
    label: 'Highway Stop-Start Pattern Count',
    description: 'Number of highway-mode stop-start patterns supporting the estimate.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic support count.',
  },
  stop_start_pattern_urban_count: {
    label: 'Urban Stop-Start Pattern Count',
    description: 'Number of urban-mode stop-start patterns supporting the estimate.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic support count.',
  },
  close_proximity_score: {
    label: 'Brake-Turn Manoeuvre Alert Estimate',
    description: 'Scores sustained brake-turn alert patterns.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    minSamples: 1,
    calibrationNote: 'Low-evidence proxy; no object proximity, other road user, or avoided collision is measured.',
  },
  jerk_score: {
    label: 'Smoothness Index',
    description: 'Scores acceleration jerk calculated from route-speed samples.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 3,
    calibrationNote: 'Dependent on GPS sampling cadence and filtering.',
  },
  jerk_event_count: {
    label: 'Jerk Event Count',
    description: 'Number of acceleration-jerk events contributing to smoothness.',
    dataSources: ['gps'],
    minDistanceKm: 0,
    calibrationNote: 'GPS sampling dependent count.',
  },
  smoothness_index: {
    label: 'Smoothness Index Value',
    description: 'Acceleration-jerk summary exposed with the jerk score.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    calibrationNote: 'GPS motion estimate.',
  },
  eco_driving_score: {
    label: 'Eco Driving Estimate',
    description: 'Estimates efficient cruise and idling patterns.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 3,
    calibrationNote: 'Not calibrated to fuel or energy consumption.',
  },
  cruise_score: {
    label: 'Cruise Score',
    description: 'Speed-stability contribution to eco driving.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    calibrationNote: 'Provisional speed-stability conversion.',
  },
  svi_score: {
    label: 'Speed Variability Score',
    description: 'Scores speed variation relative to observed road type.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'Road-type-stratified GPS estimate.',
  },
  speed_variability_index: {
    label: 'Speed Variability Index',
    description: 'Coefficient-based measure of moving-speed variability.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    calibrationNote: 'GPS estimate; affected by traffic conditions.',
  },
  svi_moving_sample_count: {
    label: 'Speed Variability Sample Count',
    description: 'Moving GPS speed samples supporting the variability score.',
    dataSources: ['gps'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic support count.',
  },
  fuel_band_score: {
    label: 'Fuel Band Score',
    description: 'Scores time spent in speed bands associated with steady driving.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 3,
    calibrationNote: 'Efficiency proxy; OBD RPM/throttle refine this score when connected.',
  },
  obd_powertrain_sample_count: {
    label: 'OBD Powertrain Sample Count',
    description: 'Number of route samples with OBD RPM or throttle evidence.',
    dataSources: ['obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic support count for optional OBD-II evidence.',
  },
  obd_idle_seconds: {
    label: 'OBD Engine Idle Seconds',
    description: 'Low-speed seconds with engine RPM present, used to refine avoidable idle scoring.',
    dataSources: ['obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Depends on supported RPM PID and sample cadence.',
  },
  obd_over_rev_count: {
    label: 'OBD Over-Rev Count',
    description: 'Count of RPM samples above the provisional over-rev threshold.',
    dataSources: ['obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Vehicle gearing and engine type are not model-specific yet.',
  },
  obd_high_throttle_count: {
    label: 'OBD High-Throttle Count',
    description: 'Count of high-throttle acceleration samples used as a physical correlate for rapid acceleration.',
    dataSources: ['obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Depends on supported throttle-position PID and sample cadence.',
  },
  optimal_band_ratio: {
    label: 'Optimal Speed Band Ratio',
    description: 'Share of accepted samples in the estimated efficient speed band.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    calibrationNote: 'Efficiency proxy.',
  },
  high_speed_ratio: {
    label: 'High Speed Ratio',
    description: 'Share of accepted samples in a high-speed band.',
    dataSources: ['gps'],
    minDistanceKm: 0.5,
    calibrationNote: 'Speed-band proxy.',
  },
  city_crawl_ratio: {
    label: 'City Crawl Ratio',
    description: 'Share of accepted samples in low urban moving speeds.',
    dataSources: ['gps'],
    minDistanceKm: 0.5,
    calibrationNote: 'Traffic and efficiency proxy.',
  },
  merge_score: {
    label: 'Merge Score',
    description: 'Scores acceleration patterns during detected merge events.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    minSamples: 1,
    calibrationNote: 'GPS manoeuvre estimate.',
  },
  merge_event_count: {
    label: 'Merge Event Count',
    description: 'Number of GPS patterns classified as merge events.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'GPS manoeuvre estimate.',
  },
  poor_merge_count: {
    label: 'Poor Merge Count',
    description: 'Number of detected merge patterns receiving poor classification.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'GPS manoeuvre estimate.',
  },
  harsh_merge_count: {
    label: 'Harsh Merge Count',
    description: 'Number of detected high-intensity merge acceleration patterns.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'GPS manoeuvre estimate.',
  },
  smooth_braking_score: {
    label: 'Smooth Braking Score',
    description: 'Scores smooth stops relative to detected braking stops.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    minSamples: 1,
    calibrationNote: 'Requires observed stop events.',
  },
  smooth_braking_ratio: {
    label: 'Smooth Braking Ratio',
    description: 'Share of detected stops classified as smooth braking.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Requires observed stop events.',
  },
  harsh_stops_count: {
    label: 'Harsh Stops Count',
    description: 'Number of detected stops classified as harsh.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'GPS-derived stop classification.',
  },
  smooth_stops_count: {
    label: 'Smooth Stops Count',
    description: 'Number of detected stops classified as smooth.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'GPS-derived stop classification.',
  },
  engine_stress_score: {
    label: 'Engine Stress Score',
    description: 'Estimates high-speed acceleration stress, refined by OBD RPM/throttle when connected.',
    dataSources: ['gps_events', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'OBD powertrain telemetry is optional; GPS events remain the fallback.',
  },
  high_speed_accel_count: {
    label: 'High-Speed Acceleration Count',
    description: 'Number of high-speed acceleration patterns supporting engine stress.',
    dataSources: ['gps_events', 'obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'OBD high-throttle samples refine stress when available.',
  },
  trip_tire_wear_units: {
    label: 'Tire Wear Units',
    description: 'Diagnostic units from harsh-brake and sharp-turn speeds.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Reference-speed model is provisional; not physical tread wear.',
  },
  trip_tire_wear_missing_speed_event_count: {
    label: 'Tire Wear Events Without Speed',
    description: 'Wear-related events excluded from speed scaling due to missing speed.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic data-quality count.',
  },
  speed_creep_score: {
    label: 'Speed Creep Score',
    description: 'Scores sustained drift above an inferred or observed speed context.',
    dataSources: ['gps', 'speed_limit_osm'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'Requires sufficient route context.',
  },
  speed_creep_event_count: {
    label: 'Speed Creep Event Count',
    description: 'Number of sustained speed-creep patterns.',
    dataSources: ['gps', 'speed_limit_osm'],
    minDistanceKm: 0,
    calibrationNote: 'Depends on speed-limit context.',
  },
  heading_drift_beta_score: {
    label: 'GPS Attention Signal Score',
    description: 'Scores repeated GPS heading-drift windows as an attention signal diagnostic.',
    dataSources: ['gps'],
    minDistanceKm: 0.5,
    minSamples: 2,
    status: BETA_FEATURE_POLICIES.headingDrift.status,
    calibrationNote: BETA_FEATURE_POLICIES.headingDrift.userLabel,
  },
  heading_drift_beta_level: {
    label: 'GPS Attention Signal Level',
    description: 'Categorised GPS attention signal diagnostic level.',
    dataSources: ['gps'],
    minDistanceKm: 0.5,
    status: BETA_FEATURE_POLICIES.headingDrift.status,
    calibrationNote: BETA_FEATURE_POLICIES.headingDrift.userLabel,
  },
  heading_drift_beta_window_count: {
    label: 'GPS Attention Signal Window Count',
    description: 'Number of GPS heading windows supporting the attention signal diagnostic.',
    dataSources: ['gps'],
    minDistanceKm: 0,
    status: BETA_FEATURE_POLICIES.headingDrift.status,
    calibrationNote: BETA_FEATURE_POLICIES.headingDrift.userLabel,
  },
  hill_driving_score: {
    label: 'Hill Driving Score',
    description: 'Scores harsh acceleration or braking on altitude-derived grades.',
    dataSources: ['gps', 'gps_altitude'],
    minDistanceKm: 0.5,
    minSamples: 3,
    calibrationNote: 'Altitude-derived grade estimate.',
  },
  hill_infraction_count: {
    label: 'Hill Infraction Count',
    description: 'Number of grade-window events supporting the hill score.',
    dataSources: ['gps', 'gps_altitude'],
    minDistanceKm: 0,
    calibrationNote: 'Altitude-derived grade estimate.',
  },
  parking_approach_score: {
    label: 'Parking Approach Score',
    description: 'Scores terminal deceleration and turns approaching a stop.',
    dataSources: ['gps'],
    minDistanceKm: 0,
    minSamples: 3,
    calibrationNote: 'GPS terminal-manoeuvre estimate.',
  },
  parking_stop_duration_seconds: {
    label: 'Parking Stop Duration',
    description: 'Terminal stopped duration detected in the parking approach window.',
    dataSources: ['gps_timestamps'],
    minDistanceKm: 0,
    calibrationNote: 'GPS terminal-manoeuvre estimate.',
  },
  brake_onset_smoothness_score: {
    label: 'Brake Onset Smoothness Score',
    description: 'Scores ramp-up smoothness at the onset of braking sequences.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'GPS-derived braking proxy.',
  },
  avg_brake_onset_ramp_seconds: {
    label: 'Average Brake Onset Ramp',
    description: 'Average observed ramp duration for braking onset.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    calibrationNote: 'Available only with qualifying braking sequences.',
  },
  brake_onset_sequence_count: {
    label: 'Brake Onset Sequence Count',
    description: 'Number of braking sequences supporting onset smoothness.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic support count.',
  },
  cornering_consistency_score: {
    label: 'Cornering Consistency Score',
    description: 'Scores consistency of GPS-derived lateral acceleration in corners.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 1,
    calibrationNote: 'GPS-derived lateral acceleration estimate.',
  },
  mean_lateral_g: {
    label: 'Mean Lateral G',
    description: 'Mean estimated lateral acceleration during observed corners.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    calibrationNote: 'GPS-derived estimate.',
  },
  peak_lateral_g: {
    label: 'Peak Lateral G',
    description: 'Peak estimated lateral acceleration during observed corners.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    calibrationNote: 'GPS-derived estimate.',
  },
  corner_sample_count: {
    label: 'Corner Sample Count',
    description: 'Number of corner observations supporting consistency scoring.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic support count.',
  },
  braking_efficiency_score: {
    label: 'Braking Efficiency Score',
    description: 'Scores controlled speed reduction across braking sequences.',
    dataSources: ['gps', 'obd_bluetooth'],
    minDistanceKm: 0.5,
    minSamples: 1,
    calibrationNote: 'GPS-derived braking proxy.',
  },
  highway_compliance_score: {
    label: 'Highway Compliance Score',
    description: 'Speed-limit compliance score on highway segments.',
    dataSources: ['gps', 'speed_limit_osm'],
    minDistanceKm: 0.5,
    calibrationNote: 'Depends on speed-limit source availability.',
  },
  urban_compliance_score: {
    label: 'Urban Compliance Score',
    description: 'Speed-limit compliance score on urban segments.',
    dataSources: ['gps', 'speed_limit_osm'],
    minDistanceKm: 0.5,
    calibrationNote: 'Depends on speed-limit source availability.',
  },
  residential_compliance_score: {
    label: 'Residential Compliance Score',
    description: 'Speed-limit compliance score on residential segments.',
    dataSources: ['gps', 'speed_limit_osm'],
    minDistanceKm: 0.5,
    calibrationNote: 'Depends on speed-limit source availability.',
  },
  overall_compliance_score: {
    label: 'Overall Compliance Score',
    description: 'Aggregated speed-limit compliance across observed road segments.',
    dataSources: ['gps', 'speed_limit_osm'],
    minDistanceKm: 0.5,
    minSamples: 1,
    calibrationNote: 'Depends on observed or inferred speed-limit context.',
  },
  overtake_quality_score: {
    label: 'Overtake Quality Score',
    description: 'Development diagnostic estimate of detected overtake manoeuvres.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    minSamples: 0,
    status: BETA_FEATURE_POLICIES.overtakePattern.status,
    calibrationNote: BETA_FEATURE_POLICIES.overtakePattern.userLabel,
  },
  overtake_score: {
    label: 'Overtake Legacy Score',
    description: 'Reserved legacy overtake score field retained for compatibility.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Unavailable; development diagnostic quality is reported separately.',
  },
  aggressive_driving_score: {
    label: 'Aggressive Driving Score',
    description: 'Aggregates detected high-intensity driving events.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'Coaching estimate from event detection.',
  },
  aggressive_grade: {
    label: 'Aggressive Driving Grade',
    description: 'Categorical presentation of aggressive-driving score.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Presentation band derived from a coaching estimate.',
  },
  defensive_driving_score: {
    label: 'Defensive Driving Estimate',
    description: 'Aggregates smooth and lower-risk detected behaviours.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    minSamples: 2,
    calibrationNote: 'Coaching estimate from event detection.',
  },
  lane_changing_score: {
    label: 'Lane Changing Diagnostic',
    description: 'Diagnostic lane-changing rate and simultaneous-braking evidence on highway segments.',
    dataSources: ['gps', 'device_motion_imu'],
    sources: ['gps', 'imu_yaw'],
    minDistanceKm: 5,
    minSamples: 2,
    evidence_minimum: { distance_km: 5, sample_count: 2 },
    status: BETA_FEATURE_POLICIES.laneChanging.status,
    graduationCriteria: BETA_FEATURE_POLICIES.laneChanging.graduationCriteria,
    calibrationNote: 'Diagnostic only and currently weighted 0% in Safety. Graduation requires at least 85% agreement on 200 dashcam-reviewed labeled trips and curved-road false positives below 10%. Curved-road suppression and speed-specific IMU yaw thresholds are active.',
    calibration_note: 'Diagnostic only and currently weighted 0% in Safety. Graduation requires at least 85% agreement on 200 dashcam-reviewed labeled trips and curved-road false positives below 10%. Curved-road suppression and speed-specific IMU yaw thresholds are active.',
    affected_components: [],
  },
  lane_change_count: {
    label: 'Lane Change Diagnostic Count',
    description: 'Count of detected lane-change manoeuvres.',
    dataSources: ['gps_events', 'device_motion_imu'],
    minDistanceKm: 5,
    minSamples: 2,
    status: BETA_FEATURE_POLICIES.laneChanging.status,
    calibrationNote: BETA_FEATURE_POLICIES.laneChanging.userLabel,
  },
  defensive_grade: {
    label: 'Defensive Driving Grade',
    description: 'Categorical presentation of defensive-driving estimate.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Presentation band derived from a coaching estimate.',
  },
  fatigue_risk_score: {
    label: 'Fatigue Risk Score',
    description: 'Driving-duration and time-based fatigue proxy.',
    dataSources: ['gps_timestamps'],
    minDistanceKm: 0,
    minSamples: 1,
    calibrationNote: 'Proxy only; not a diagnosis or alertness measurement.',
  },
  highway_score: {
    label: 'Highway Segment Score',
    description: 'Overall score recalculated for qualifying highway segments.',
    dataSources: ['gps_events'],
    minDistanceKm: 2,
    calibrationNote: 'Available only with sufficient highway segment distance.',
  },
  urban_score: {
    label: 'Urban Segment Score',
    description: 'Overall score recalculated for qualifying urban segments.',
    dataSources: ['gps_events'],
    minDistanceKm: 2,
    calibrationNote: 'Available only with sufficient urban segment distance.',
  },
  residential_score: {
    label: 'Residential Segment Score',
    description: 'Overall score recalculated for qualifying residential segments.',
    dataSources: ['gps_events'],
    minDistanceKm: 2,
    calibrationNote: 'Available only with sufficient residential segment distance.',
  },
  dominant_road_type: {
    label: 'Dominant Road Type',
    description: 'Road class contributing the greatest qualifying route distance.',
    dataSources: ['gps'],
    minDistanceKm: 0.5,
    calibrationNote: 'Classified from route speed context.',
  },
  safety_condition_bonus: {
    label: 'Safety Condition Bonus',
    description: 'Adjustment for measured caution in slippery-condition proxy windows.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Weather-condition proxy, not measured road friction.',
  },
  wet_signal_count: {
    label: 'Wet Signal Count',
    description: 'Number of braking-distance windows suggesting slippery conditions.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Proxy only; not measured road friction.',
  },
  wet_ratio: {
    label: 'Wet Signal Ratio',
    description: 'Share of candidate windows suggesting slippery conditions.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Proxy only; not measured road friction.',
  },
  avg_distance_ratio: {
    label: 'Average Stopping Distance Ratio',
    description: 'Average stopping-distance ratio supporting the road-condition proxy.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Proxy only; not measured road friction.',
  },
  harsh_brakes_count: {
    label: 'Harsh Brakes',
    description: 'Count of detected harsh braking events.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Detection threshold based event count.',
  },
  rapid_accel_count: {
    label: 'Rapid Acceleration Events',
    description: 'Count of detected rapid acceleration events.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Detection threshold based event count.',
  },
  sharp_turns_count: {
    label: 'Sharp Turns',
    description: 'Count of detected sharp-turn events.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'GPS heading based event count.',
  },
  possible_crash_count: {
    label: 'Possible Incident Signals',
    description: 'Count of possible crash or incident signals detected from abrupt IMU motion followed by little movement.',
    dataSources: ['gps', 'device_motion_imu', 'android_activity_recognition'],
    minDistanceKm: 0,
    calibrationNote: 'Emergency workflow trigger only; not a crash diagnosis and unavailable without device motion samples.',
    permission_required: 'motion_sensors',
    permissionRequiredNote: 'Device motion/IMU access is required before Road Sage can evaluate impact-like movement for possible incident detection.',
  },
  speeding_events_count: {
    label: 'Speeding Events',
    description: 'Count of detected speeding events.',
    dataSources: ['gps_events', 'speed_limit_osm'],
    minDistanceKm: 0,
    calibrationNote: 'Depends on speed-limit evidence.',
  },
  heading_deviation_count: {
    label: 'Heading Deviation Events',
    description: 'Count of heading-deviation diagnostic events.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic only.',
  },
  heading_deviation_legacy_count: {
    label: 'Heading Events (Legacy)',
    description: 'Count of legacy GPS heading events migrated from the retired lane-change event type.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Legacy diagnostic only; no lane boundary crossing was measured.',
  },
  stop_start_pattern_count: {
    label: 'Stop-Start Patterns',
    description: 'Count of detected stop-start diagnostic patterns.',
    dataSources: ['gps_events'],
    minDistanceKm: 5,
    calibrationNote: 'Does not measure following distance.',
  },
  distraction_events_count: {
    label: 'Distraction Pattern Events',
    description: 'Count of GPS erratic-speed diagnostic patterns.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic proxy; not evidence of phone interaction.',
  },
  close_proximity_count: {
    label: 'Brake-Turn Manoeuvre Alerts',
    description: 'Count of sustained brake-turn alert patterns.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Proxy only; no object detection, other road user, or avoided collision is measured.',
  },
  overtake_event_count: {
    label: 'Overtake Patterns (Development)',
    description: 'Count of development-only detected overtake patterns.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    status: BETA_FEATURE_POLICIES.overtakePattern.status,
    calibrationNote: BETA_FEATURE_POLICIES.overtakePattern.userLabel,
  },
  phone_use_window_count: {
    label: 'Phone Use Windows',
    description: 'Count of confirmed phone-use windows during the trip.',
    dataSources: ['phone_use_usage_access'],
    minDistanceKm: 0,
    calibrationNote: 'Android Usage Access required.',
  },
  phone_proxy_risk: {
    label: 'Phone Proxy Diagnostic',
    description: 'Categorical GPS pattern diagnostic formerly associated with phone risk.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Diagnostic only; not confirmed phone-use evidence.',
  },
  phone_proxy_diagnostic_score: {
    label: 'Phone Proxy Diagnostic Score',
    description: 'GPS-pattern severity score retained outside confirmed phone-use scoring.',
    dataSources: ['gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Diagnostic only; not confirmed phone-use evidence.',
  },
  phone_proxy_count: {
    label: 'Phone Proxy Pattern Count',
    description: 'Number of GPS distraction-like patterns retained as diagnostics.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Diagnostic proxy only; not phone-use evidence.',
  },
  phone_use_total_seconds: {
    label: 'Phone Use Duration',
    description: 'Total confirmed phone-use seconds during the trip.',
    dataSources: ['phone_use_usage_access'],
    minDistanceKm: 0,
    calibrationNote: 'Android Usage Access required.',
  },
  phone_use_pct_of_trip: {
    label: 'Phone Use Trip Percentage',
    description: 'Share of recorded drive duration with confirmed phone use.',
    dataSources: ['phone_use_usage_access', 'gps_timestamps'],
    minDistanceKm: 0,
    calibrationNote: 'Android Usage Access required.',
  },
  phone_use_high_confidence_count: {
    label: 'High-Confidence Phone Use Count',
    description: 'Number of confirmed phone-use windows marked high confidence.',
    dataSources: ['phone_use_usage_access'],
    minDistanceKm: 0,
    calibrationNote: 'Android Usage Access required.',
  },
  phone_use_risk: {
    label: 'Phone Use Risk',
    description: 'Categorical risk presentation of confirmed phone-use evidence.',
    dataSources: ['phone_use_usage_access'],
    minDistanceKm: 0.5,
    calibrationNote: 'Android Usage Access required.',
  },
  braking_sequence_count: {
    label: 'Braking Sequence Count',
    description: 'Count of qualifying braking sequences.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    calibrationNote: 'Detection threshold based count.',
  },
  brake_onset_smoothness_grade: {
    label: 'Brake Onset Smoothness Grade',
    description: 'Categorical presentation of brake-onset smoothness score.',
    dataSources: ['gps'],
    minDistanceKm: 0.5,
    calibrationNote: 'Presentation band derived from a GPS proxy.',
  },
  braking_efficiency_grade: {
    label: 'Braking Efficiency Grade',
    description: 'Categorical presentation of braking-efficiency score.',
    dataSources: ['gps'],
    minDistanceKm: 0.5,
    calibrationNote: 'Presentation band derived from a GPS proxy.',
  },
  overtake_count: {
    label: 'Overtake Pattern Count (Development)',
    description: 'Count of development-only overtake patterns scored for quality.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    status: BETA_FEATURE_POLICIES.overtakePattern.status,
    calibrationNote: BETA_FEATURE_POLICIES.overtakePattern.userLabel,
  },
  unsafe_reentry_count: {
    label: 'Unsafe Re-entry Count (Development)',
    description: 'Count of development-only overtake re-entry alerts.',
    dataSources: ['gps_events'],
    minDistanceKm: 0,
    status: BETA_FEATURE_POLICIES.overtakePattern.status,
    calibrationNote: BETA_FEATURE_POLICIES.overtakePattern.userLabel,
  },
  slippery_proxy: {
    label: 'Weather Context',
    description: 'Source-attributed weather context from Open-Meteo when available or GPS stopping-distance patterns as a fallback.',
    dataSources: ['open_meteo_weather', 'gps_events'],
    minDistanceKm: 0.5,
    calibrationNote: 'Source-attributed context only; Road Sage does not measure road-surface condition.',
  },
  road_type: {
    label: 'Road Type',
    description: 'Route road classification recorded for export.',
    dataSources: ['gps'],
    minDistanceKm: 0,
    calibrationNote: 'Classification may be inferred where map context is absent.',
  },
  night_driving: {
    label: 'Night Driving',
    description: 'Whether the recorded trip falls within configured night hours.',
    dataSources: ['gps_timestamps'],
    minDistanceKm: 0,
    calibrationNote: 'Time-window classification.',
  },
  speed_limit_sources: {
    label: 'Speed Limit Sources',
    description: 'Provenance labels for speed-limit values used during scoring.',
    dataSources: ['speed_limit_osm', 'gps_inferred_speed_limit'],
    minDistanceKm: 0,
    calibrationNote: 'Provenance field rather than a numeric score.',
  },
  speed_limit_default_countries: {
    label: 'Speed Limit Default Countries',
    description: 'Country defaults used when map speed-limit data was unavailable.',
    dataSources: ['speed_limit_osm'],
    minDistanceKm: 0,
    calibrationNote: 'Provenance field rather than a numeric score.',
  },
  gps_point_count: {
    label: 'GPS Point Count',
    description: 'Number of route samples retained in the exported trip.',
    dataSources: ['gps'],
    minDistanceKm: 0,
    calibrationNote: 'Support-data count.',
  },
  ubi_score: {
    label: 'UBI-Style Score',
    description: 'Weighted driver score card summary over completed-trip history.',
    dataSources: ['trip_scores', 'gps_events'],
    minDistanceKm: 50,
    calibrationNote: 'Internal estimate only; not insurer validated.',
  },
  ubi_mileage_score: {
    label: '12-Month Mileage Score',
    description: 'Scores annualised mileage relative to a configurable target.',
    dataSources: ['trip_distance_history'],
    minDistanceKm: 50,
    calibrationNote: 'Target and spread assumptions are configurable approximations.',
  },
  ubi_time_of_day_score: {
    label: 'Time of Day Score',
    description: 'Penalises recorded night-driving exposure.',
    dataSources: ['trip_timestamps'],
    minDistanceKm: 50,
    calibrationNote: 'TIME_OF_DAY_NIGHT_MULTIPLIER 150 provisional.',
  },
  ubi_hard_braking_score: {
    label: 'Hard Braking Score',
    description: 'Penalises harsh-braking events per 100 km.',
    dataSources: ['gps_events', 'trip_distance_history'],
    minDistanceKm: 50,
    calibrationNote: 'Penalty per 100 km is provisional.',
  },
  ubi_acceleration_score: {
    label: 'Rapid Acceleration Score',
    description: 'Penalises rapid-acceleration events per 100 km.',
    dataSources: ['gps_events', 'trip_distance_history'],
    minDistanceKm: 50,
    calibrationNote: 'Penalty per 100 km is provisional.',
  },
  ubi_cornering_score: {
    label: 'Cornering Score',
    description: 'Penalises sharp-turn events per 100 km.',
    dataSources: ['gps_events', 'trip_distance_history'],
    minDistanceKm: 50,
    calibrationNote: 'Penalty per 100 km is provisional.',
  },
  ubi_speed_compliance_score: {
    label: 'Speed Compliance Score',
    description: 'Penalises speeding events per 100 km.',
    dataSources: ['gps_events', 'trip_distance_history'],
    minDistanceKm: 50,
    calibrationNote: 'Penalty per 100 km is provisional.',
  },
});

export const COMPONENT_METRIC_KEYS = Object.freeze({
  overall: 'score_overall',
  safety: 'score_safety',
  smoothness: 'score_smoothness',
  eco: 'score_eco',
  intersection: 'intersection_score',
  distraction: 'distraction_score',
  phone_use: 'phone_use_score',
  stop_start_pattern: 'stop_start_pattern_score',
  close_proximity: 'close_proximity_score',
  smoothness_index: 'jerk_score',
  eco_driving: 'eco_driving_score',
  speed_variability: 'svi_score',
  fuel_band: 'fuel_band_score',
  merge: 'merge_score',
  smooth_braking: 'smooth_braking_score',
  engine_stress: 'engine_stress_score',
  speed_creep: 'speed_creep_score',
  heading_drift_beta: 'heading_drift_beta_score',
  hill_driving: 'hill_driving_score',
  parking_approach: 'parking_approach_score',
  brake_onset_smoothness: 'brake_onset_smoothness_score',
  cornering_consistency: 'cornering_consistency_score',
  braking_efficiency: 'braking_efficiency_score',
  speed_limit_compliance: 'overall_compliance_score',
  overtake_quality: 'overtake_quality_score',
  aggressive_driving: 'aggressive_driving_score',
  defensive_driving: 'defensive_driving_score',
  lane_changing: 'lane_changing_score',
  fatigue_risk: 'fatigue_risk_score',
});

export const CSV_METRIC_COLUMNS = Object.freeze({
  'Duration (min)': 'duration_seconds',
  'Distance (km)': 'distance_km',
  'Avg Speed (km/h)': 'avg_speed_kmh',
  'Avg Moving Speed (km/h)': 'avg_running_speed_kmh',
  'Max Speed (km/h)': 'max_speed_kmh',
  Score: 'score_overall',
  Safety: 'score_safety',
  Smoothness: 'score_smoothness',
  Eco: 'score_eco',
  'Eco Score Estimate': 'score_eco',
  'Smoothness Index': 'jerk_score',
  'Eco Driving Estimate': 'eco_driving_score',
  'Stop-Start Pattern Estimate': 'stop_start_pattern_score',
  'Attention-Pattern Estimate': 'distraction_score',
  'Approach-Stop Estimate': 'intersection_score',
  'Aggressive Score': 'aggressive_driving_score',
  'Aggressive Grade': 'aggressive_grade',
  'Defensive Driving Estimate': 'defensive_driving_score',
  'Defensive Grade': 'defensive_grade',
  SVI: 'speed_variability_index',
  'Fuel Band': 'fuel_band_score',
  'Smooth Braking': 'smooth_braking_ratio',
  'Engine Stress': 'engine_stress_score',
  'Tire Wear Units': 'trip_tire_wear_units',
  'GPS Attention Signal': 'heading_drift_beta_level',
  'Phone Proxy (Diagnostic)': 'phone_proxy_risk',
  'Parking Score': 'parking_approach_score',
  'Highway Score': 'highway_score',
  'Urban Score': 'urban_score',
  'Residential Score': 'residential_score',
  'Dominant Road Type': 'dominant_road_type',
  'Brake Onset Smoothness Score': 'brake_onset_smoothness_score',
  'Avg Brake Onset Ramp (s)': 'avg_brake_onset_ramp_seconds',
  'Brake Onset Smoothness Grade': 'brake_onset_smoothness_grade',
  'Phone Use Windows': 'phone_use_window_count',
  'Phone Use Total Seconds': 'phone_use_total_seconds',
  'Phone Use Risk': 'phone_use_risk',
  'Phone Use Score (Usage Access)': 'phone_use_score',
  'Phone Use Pct Trip': 'phone_use_pct_of_trip',
  'Cornering Consistency Score': 'cornering_consistency_score',
  'Mean Lateral G': 'mean_lateral_g',
  'Peak Lateral G': 'peak_lateral_g',
  'Braking Efficiency Score': 'braking_efficiency_score',
  'Braking Efficiency Grade': 'braking_efficiency_grade',
  'Braking Sequence Count': 'braking_sequence_count',
  'Highway Compliance Score': 'highway_compliance_score',
  'Urban Compliance Score': 'urban_compliance_score',
  'Residential Compliance Score': 'residential_compliance_score',
  'Overall Compliance Score': 'overall_compliance_score',
  'Speed Limit Sources': 'speed_limit_sources',
  'Speed Limit Default Countries': 'speed_limit_default_countries',
  'Overtake Quality Score (Development Diagnostic)': 'overtake_quality_score',
  'Overtake Pattern Count (Development Diagnostic)': 'overtake_count',
  'Unsafe Re-entry Count (Development Diagnostic)': 'unsafe_reentry_count',
  'Weather Context': 'slippery_proxy',
  'Safety Condition Bonus': 'safety_condition_bonus',
  'Road Type': 'road_type',
  'Harsh Brakes': 'harsh_brakes_count',
  'Rapid Accels': 'rapid_accel_count',
  'Sharp Turns': 'sharp_turns_count',
  'Speeding Events': 'speeding_events_count',
  'Heading Deviation Events (Diagnostic)': 'heading_deviation_count',
  'Heading Events (Legacy)': 'heading_deviation_legacy_count',
  'Stop-Start Patterns': 'stop_start_pattern_count',
  'Erratic Speed Events': 'distraction_events_count',
  'Brake-Turn Manoeuvre Alerts': 'close_proximity_count',
  'Overtake Patterns (Development Diagnostic)': 'overtake_event_count',
  'Night Driving': 'night_driving',
  'GPS Point Count': 'gps_point_count',
});

export const CSV_RAW_COLUMNS = Object.freeze([
  'ID',
  'Start Time',
  'End Time',
  'Event Feedback Accurate',
  'Event Feedback Wrong',
  'Event Feedback JSON',
  'Route Points JSON',
  'Driving Events JSON',
]);

export const MONTHLY_PDF_METRIC_KEYS = Object.freeze([
  'distance_km',
  'duration_seconds',
  'score_overall',
  'score_safety',
  'score_smoothness',
  'score_eco',
  'harsh_brakes_count',
  'speeding_events_count',
]);

export const UBI_PDF_METRIC_KEYS = Object.freeze([
  'ubi_score',
  'ubi_mileage_score',
  'ubi_time_of_day_score',
  'ubi_hard_braking_score',
  'ubi_acceleration_score',
  'ubi_cornering_score',
  'ubi_speed_compliance_score',
]);

export const UBI_CATEGORY_METRIC_KEYS = Object.freeze({
  mileage: 'ubi_mileage_score',
  timeOfDay: 'ubi_time_of_day_score',
  hardBraking: 'ubi_hard_braking_score',
  acceleration: 'ubi_acceleration_score',
  cornering: 'ubi_cornering_score',
  speedCompliance: 'ubi_speed_compliance_score',
});

export function formatMetricMetadata(metricKey) {
  const metric = METRIC_REGISTRY[metricKey];
  if (!metric) return '';
  const sources = metric.dataSources.map(formatDataSourceLabel).join('; ');
  return `${metric.label}: ${metric.description} Sources: ${sources}. Minimum distance: ${metric.minDistanceKm} km. ${metric.calibrationNote}`;
}

export function formatDataSourceLabel(source) {
  if (!source) return '';
  const key = String(source);
  return DATA_SOURCE_LABELS[key] || key
    .split('_')
    .filter(Boolean)
    .map((part) => part.toUpperCase() === part ? part : part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}
