package com.drivesense.app;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;

/**
 * Parity guard for the cell-hash privacy geometry shared with
 * src/lib/privacyZones.js. The fixture below was generated by the JS
 * createPrivacyCellHashes for a zone at 43.65,-79.38 with a 100 m radius and a
 * 50 m cell size; the expectations are the JS isPointInPrivacyZone verdicts for
 * the same points. If either side's hashing or guard math drifts, this fails.
 */
public class PrivacyZoneCheckerTest {

    private static final String[] JS_CELL_HASHES = new String[] {
        "pzc_10x6pa0", "pzc_10x6pa1", "pzc_10x6pan", "pzc_10x6pao", "pzc_10x6pap",
        "pzc_1b6o01r", "pzc_1b6o01s", "pzc_1b6o02e", "pzc_1b6o02f", "pzc_1b6o02g",
        "pzc_1gcy2hg", "pzc_1gcy2hh", "pzc_1gcy2hi", "pzc_1gcy2i4", "pzc_1gcy2i5",
        "pzc_1gcy2i6", "pzc_1gcy2i7", "pzc_1tqt6c6", "pzc_1tqt6c7", "pzc_1tqt6c8",
        "pzc_1tqt6cu", "pzc_1tqt6cv", "pzc_1tqt6cw", "pzc_1tqt6cx", "pzc_njblf9",
        "pzc_njblfa", "pzc_njblfb", "pzc_njblfx", "pzc_njblfy", "pzc_njblfz",
        "pzc_njblg0"
    };

    /**
     * The same zone hashed under the keyed scheme, generated by the JS
     * createPrivacyCellHashes with the cell key below (bytes 0x00..0x1f). Keyed
     * cells only resolve on a device that holds the key, so this fixture is what
     * proves Android computes the same HMAC the web app does.
     */
    private static final String[] JS_KEYED_CELL_HASHES = new String[] {
        "pzc2_1ca105137fd8c9e1", "pzc2_278b10c3a7c07eea", "pzc2_2dab32163366215c",
        "pzc2_32fdbc59f03a7e51", "pzc2_3e14011cec69abc6", "pzc2_3fc471f4214e0d05",
        "pzc2_64b31886878fd13f", "pzc2_69791ffe50fa1c10", "pzc2_6c05607d691a95ed",
        "pzc2_6e92fd50048cfc88", "pzc2_704d32ede7a80678", "pzc2_71b1c0a23ef47c43",
        "pzc2_74646254f9a3a7e3", "pzc2_76ff9020dbe7b9f7", "pzc2_8676ded58efb8e3c",
        "pzc2_92f3c392c65e1735", "pzc2_95a3ce5482bbf1f9", "pzc2_9c5133cff44eb664",
        "pzc2_a45eba355decbc5c", "pzc2_a592bd23b39f7eb4", "pzc2_a864a61aedc79b99",
        "pzc2_a8b9949279e447ab", "pzc2_ae280eb5f673c5a5", "pzc2_c1f338d46c7554a3",
        "pzc2_c31f0f6b6383e981", "pzc2_ccf28de04790c181", "pzc2_d0721c84e8de248c",
        "pzc2_d3486a1fa3501fff", "pzc2_eabb19761977fc22", "pzc2_f0532bbfb067d958",
        "pzc2_ff83a1dafcac68b3"
    };

    /** offset north of the zone center (m), JS verdict at guard 0, JS verdict at guard 50. */
    private static final double[][] JS_SAMPLES = new double[][] {
        { 43.65,      1d, 1d },
        { 43.650539,  1d, 1d },
        { 43.651078,  1d, 1d },
        { 43.6513026, 0d, 1d },
        { 43.6515271, 0d, 1d },
        { 43.6517966, 0d, 0d },
        { 43.6523356, 0d, 0d },
    };

    private static JSONObject cellOnlyZone() throws Exception {
        JSONObject zone = new JSONObject();
        zone.put("id", "home");
        zone.put("label", "Home");
        zone.put("radius_m", 100);
        zone.put("privacy_cell_schema", "global_grid_v1");
        zone.put("privacy_cell_size_m", 50);
        zone.put("privacy_cell_hashes", new JSONArray(java.util.Arrays.asList(JS_CELL_HASHES)));
        zone.put("masked_for_privacy", true);
        return zone;
    }

    private static byte[] cellKey(int seed) {
        byte[] key = new byte[32];
        for (int i = 0; i < key.length; i++) key[i] = (byte) (i + seed);
        return key;
    }

    private static JSONObject keyedZone() throws Exception {
        JSONObject zone = cellOnlyZone();
        zone.put("privacy_cell_schema", "keyed_grid_v2");
        zone.put("privacy_cell_hashes", new JSONArray(java.util.Arrays.asList(JS_KEYED_CELL_HASHES)));
        return zone;
    }

    @Test
    public void matchesTheJavaScriptVerdictForKeyedCellsAtEveryGuardDistance() throws Exception {
        JSONObject zone = keyedZone();
        byte[] key = cellKey(0);
        for (double[] sample : JS_SAMPLES) {
            double lat = sample[0];
            assertEquals(
                "unguarded keyed verdict at lat " + lat,
                sample[1] == 1d,
                PrivacyZoneChecker.isInsidePrivacyCellZone(lat, -79.38d, zone, 0d, key)
            );
            assertEquals(
                "guarded keyed verdict at lat " + lat,
                sample[2] == 1d,
                PrivacyZoneChecker.isInsidePrivacyCellZone(lat, -79.38d, zone, 50d, key)
            );
        }
    }

    @Test
    public void treatsKeyedCellsAsPrivateWhenTheKeyIsMissing() throws Exception {
        JSONObject zone = keyedZone();
        // Far outside the zone: without the key the guard cannot be evaluated, so
        // the fix must be treated as private rather than waved through.
        assertTrue(PrivacyZoneChecker.isInsidePrivacyCellZone(12.5d, 4.25d, zone, 50d, null));
        assertTrue(PrivacyZoneChecker.isInsidePrivacyCellZone(12.5d, 4.25d, zone, 50d, new byte[0]));
    }

    @Test
    public void bindsEachCellHashToItsKey() {
        String underFirst = PrivacyZoneChecker.keyedPrivacyCellHash(297000L, 223000L, 50d, cellKey(0));
        String underSecond = PrivacyZoneChecker.keyedPrivacyCellHash(297000L, 223000L, 50d, cellKey(7));

        assertTrue(underFirst.startsWith("pzc2_"));
        assertEquals(21, underFirst.length());
        assertFalse(underFirst.equals(underSecond));
    }

    @Test
    public void matchesTheJavaScriptVerdictAtEveryGuardDistance() throws Exception {
        JSONObject zone = cellOnlyZone();
        for (double[] sample : JS_SAMPLES) {
            double lat = sample[0];
            boolean expectedUnguarded = sample[1] == 1d;
            boolean expectedGuarded = sample[2] == 1d;
            assertEquals(
                "unguarded verdict at lat " + lat,
                expectedUnguarded,
                PrivacyZoneChecker.isInsidePrivacyCellZone(lat, -79.38d, zone, 0d)
            );
            assertEquals(
                "guarded verdict at lat " + lat,
                expectedGuarded,
                PrivacyZoneChecker.isInsidePrivacyCellZone(lat, -79.38d, zone, 50d)
            );
        }
    }

    @Test
    public void guardExtendsCoverageBeyondTheUnguardedCells() throws Exception {
        JSONObject zone = cellOnlyZone();
        // 145 m north: outside the unguarded cell coverage, inside the 50 m guard.
        assertFalse(PrivacyZoneChecker.isInsidePrivacyCellZone(43.6513026d, -79.38d, zone, 0d));
        assertTrue(PrivacyZoneChecker.isInsidePrivacyCellZone(43.6513026d, -79.38d, zone, 50d));
    }

    @Test
    public void ignoresZonesWithoutCellHashes() throws Exception {
        JSONObject zone = new JSONObject();
        zone.put("id", "empty");
        zone.put("radius_m", 100);
        assertFalse(PrivacyZoneChecker.isInsidePrivacyCellZone(43.65d, -79.38d, zone, 50d));

        zone.put("privacy_cell_hashes", new JSONArray());
        assertFalse(PrivacyZoneChecker.isInsidePrivacyCellZone(43.65d, -79.38d, zone, 50d));
    }

    @Test
    public void fallsBackToTheJavaScriptCellSizeWhenTheFieldIsMissing() throws Exception {
        JSONObject zone = cellOnlyZone();
        zone.remove("privacy_cell_size_m");
        // A mismatched default would make every hash miss, which fails open.
        assertTrue(PrivacyZoneChecker.isInsidePrivacyCellZone(43.65d, -79.38d, zone, 0d));
    }
}
