package com.drivesense.app;

/**
 * Detection constants shared with the JavaScript scoring pipeline.
 *
 * GENERATED by scripts/generate-native-detection-constants.mjs from
 * src/lib/scoringConstants.js. Do not edit by hand - run `npm run native:constants`.
 *
 * The native service runs its own live detector for voice coaching only; it never
 * produces a score. Sharing these values is what stops it announcing an event that the
 * scored trip will not contain. Each field names the JS constant it mirrors.
 */
final class DetectionConstants {

    /**
     * GPS sample quality. Must match the filter the scored trip uses, or the live
     * detector reacts to points the trip engine has already discarded.
     */
    /** MAX_GPS_ACCURACY_M */
    static final float MAX_ACCURACY_M = 50.0f;
    /** MIN_POINT_DISTANCE_M */
    static final double MIN_POINT_DISTANCE_M = 8.0d;
    /** STATIONARY_SPEED_KMH */
    static final double STATIONARY_SPEED_KMH = 5.0d;
    /** MIN_TRUSTED_SPEED_KMH */
    static final double MIN_TRUSTED_SPEED_KMH = 18.0d;
    /** MAX_REASONABLE_GPS_SPEED_KMH */
    static final double MAX_SPEED_KMH = 220.0d;
    /** MAX_SAMPLE_GAP_SECONDS */
    static final long STATS_MAX_SAMPLE_GAP_SECONDS = 120L;

    /**
     * Trip acceptance. A trip the native side saves but the scorer rejects shows up as
     * an unscored record in the trip list.
     */
    /** MIN_TRIP_DURATION_SECONDS * 1000 */
    static final long MIN_TRIP_MS = 30000L;
    /** MIN_TRIP_DISTANCE_KM */
    static final double MIN_TRIP_KM = 0.1d;
    /** MAX_TERMINAL_IDLE_SECONDS */
    static final long MAX_TERMINAL_IDLE_SECONDS = 1800L;

    /**
     * Fallback night window, used when solar context is unavailable.
     */
    /** NIGHT_START_HOUR */
    static final int NIGHT_START_HOUR = 22;
    /** NIGHT_END_HOUR */
    static final int NIGHT_END_HOUR = 5;

    /**
     * Event minimum-speed gates. These were one shared LIVE_EVENT_MIN_SPEED_KMH on the
     * native side, which is why braking alerts could fire below the speed at which the
     * scored trip records a harsh brake at all.
     */
    /** MIN_SPEED_HARSH_BRAKE_KMH */
    static final double MIN_SPEED_HARSH_BRAKE_KMH = 25.0d;
    /** MIN_SPEED_RAPID_ACCEL_KMH */
    static final double MIN_SPEED_RAPID_ACCEL_KMH = 5.0d;
    /** CORNERING_MIN_SPEED_KMH */
    static final double CORNERING_MIN_SPEED_KMH = 25.0d;
    /** SHARP_TURN_MIN_HEADING_CHANGE_DEG */
    static final double SHARP_TURN_MIN_HEADING_CHANGE_DEG = 30.0d;
    /** mathUtils.js STANDARD_GRAVITY_MS2 */
    static final double STANDARD_GRAVITY_MS2 = 9.80665d;

    /**
     * Stop-start pattern. The JS detector picks its threshold set from the trip median
     * moving speed; the service approximates that with the current speed, because it
     * has no trip median until the trip ends.
     */
    /** STOP_START_URBAN_MEDIAN_SPEED_KMH */
    static final double STOP_START_URBAN_SPEED_SPLIT_KMH = 50.0d;
    /** STOP_START_DECEL_MS2 */
    static final double STOP_START_DECEL_MS2 = 2.5d;
    /** STOP_START_MIN_SPEED_KMH */
    static final double STOP_START_MIN_SPEED_KMH = 40.0d;
    /** STOP_START_SPEED_DROP_KMH */
    static final double STOP_START_SPEED_DROP_KMH = 10.0d;
    /** STOP_START_URBAN_DECEL_MS2 */
    static final double STOP_START_URBAN_DECEL_MS2 = 1.4d;
    /** STOP_START_URBAN_MIN_SPEED_KMH */
    static final double STOP_START_URBAN_MIN_SPEED_KMH = 25.0d;
    /** STOP_START_URBAN_SPEED_DROP_KMH */
    static final double STOP_START_URBAN_SPEED_DROP_KMH = 6.0d;

    /**
     * Default detection thresholds. The service reads the user value from settings and
     * falls back to these, so a fallback that disagreed with DEFAULT_SETTINGS would make
     * a fresh install detect differently from a configured one.
     */
    /** HARSH_BRAKE_MS2 */
    static final double HARSH_BRAKE_MS2 = 3.5d;
    /** RAPID_ACCEL_MS2 */
    static final double RAPID_ACCEL_MS2 = 3.0d;
    /** SHARP_TURN_G_LOW */
    static final double SHARP_TURN_G_LOW = 0.35d;
    /** HEADING_DRIFT_STD_DEG */
    static final double HEADING_DRIFT_STD_DEG = 8.0d;
    /** HEADING_DEVIATION_HIGHWAY_MIN_SPEED_KMH */
    static final double HEADING_DRIFT_HIGHWAY_SPEED_KMH = 80.0d;
    /** MANOEUVRE_ALERT_BRAKE_MS2 */
    static final double MANOEUVRE_ALERT_BRAKE_MS2 = 4.0d;
    /** MANOEUVRE_ALERT_TURN_DEG_S */
    static final double MANOEUVRE_ALERT_TURN_DEG_S = 25.0d;
    /** SPEEDING_FALLBACK_KMH */
    static final double SPEEDING_FALLBACK_KMH = 100.0d;
    /** SPEED_OVER_KMH */
    static final double SPEED_OVER_KMH = 5.0d;
    /** LONG_DRIVE_MINUTES */
    static final double LONG_DRIVE_MINUTES = 120.0d;

    /**
     * Phone-use GPS proxy. Diagnostic only on both sides: it never contributes to a
     * score, and confirmed phone use still requires Usage Access.
     */
    /** PHONE_MICRO_STEER_WINDOW_S */
    static final double PHONE_MICRO_STEER_WINDOW_S = 15.0d;
    /** PHONE_MICRO_STEER_COUNT */
    static final int PHONE_MICRO_STEER_COUNT = 6;
    /** PHONE_MICRO_STEER_MIN_DEG */
    static final double PHONE_MICRO_STEER_MIN_DEG = 3.0d;
    /** PHONE_MICRO_STEER_MAX_DEG */
    static final double PHONE_MICRO_STEER_MAX_DEG = 18.0d;
    /** PHONE_PROXY_MAX_ACCURACY_M */
    static final float PHONE_PROXY_MAX_ACCURACY_M = 20.0f;
    /** PHONE_DETECT_MIN_SPEED_KMH */
    static final double PHONE_DETECT_MIN_SPEED_KMH = 30.0d;

    /**
     * Speed-alert gating. These were hand-copied literals that happened to agree, and
     * the two sides had already drifted in behaviour: the webview applied neither the
     * sustained window nor the confidence floor, so a background trip and a foreground
     * trip over the same road could alert differently.
     * 
     * RELEASE_KMH is the hysteresis band. The over-limit state clears only below
     * (limit + margin - release), so hovering on the threshold cannot re-arm the alert.
     */
    /** appConstants.SPEED_ALERT_SUSTAINED_MS */
    static final long SPEED_ALERT_SUSTAINED_MS = 5000L;
    /** appConstants.SPEED_ALERT_MIN_CONFIDENCE */
    static final double SPEED_ALERT_MIN_CONFIDENCE = 0.55d;
    /** appConstants.SPEED_ALERT_RELEASE_KMH */
    static final double SPEED_ALERT_RELEASE_KMH = 3.0d;

    /**
     * Predictive hazard horizon.
     * 
     * The repeated-event-area warning was direction-blind on both sides: any stored
     * zone within a fixed 300 m radius was announced as being "ahead", so zones behind
     * the vehicle and on parallel and crossing roads all spoke. The radius was also the
     * wrong unit, buying 36 s of warning at 30 km/h and 10 s at 110 km/h.
     * 
     * The service now projects a forward cone and warns on seconds-to-arrival. Only the
     * geometry constants are shared: route-risk segments, the late-braking advisory and
     * the corridor graph stay on the JavaScript side, which is where that data lives.
     */
    /** appConstants.HAZARD_HORIZON_ALERT_SECONDS */
    static final double HAZARD_HORIZON_ALERT_SECONDS = 12.0d;
    /** appConstants.HAZARD_HORIZON_MIN_SECONDS */
    static final double HAZARD_HORIZON_MIN_SECONDS = 3.0d;
    /** appConstants.HAZARD_HORIZON_MIN_SECONDS_SETTING */
    static final double HAZARD_HORIZON_MIN_SECONDS_SETTING = 6.0d;
    /** appConstants.HAZARD_HORIZON_MAX_SECONDS */
    static final double HAZARD_HORIZON_MAX_SECONDS = 20.0d;
    /** appConstants.HAZARD_PROJECTION_SLACK */
    static final double HAZARD_PROJECTION_SLACK = 1.5d;
    /** appConstants.HAZARD_PROJECTION_MIN_M */
    static final double HAZARD_PROJECTION_MIN_M = 120.0d;
    /** appConstants.HAZARD_PROJECTION_MAX_M */
    static final double HAZARD_PROJECTION_MAX_M = 900.0d;
    /** appConstants.HAZARD_FORWARD_CONE_DEG */
    static final double HAZARD_FORWARD_CONE_DEG = 50.0d;
    /** appConstants.HAZARD_CORRIDOR_MAX_HALF_WIDTH_M */
    static final double HAZARD_CORRIDOR_MAX_HALF_WIDTH_M = 70.0d;
    /** appConstants.HAZARD_MIN_SPEED_KMH */
    static final double HAZARD_MIN_SPEED_KMH = 15.0d;
    /** appConstants.HAZARD_MAX_ACCURACY_M */
    static final float HAZARD_MAX_ACCURACY_M = 35.0f;
    /** appConstants.HAZARD_ALERT_GLOBAL_COOLDOWN_MS */
    static final long HAZARD_ALERT_GLOBAL_COOLDOWN_MS = 30000L;

    private DetectionConstants() {
    }
}
