// @ts-check
// The Settings area manifest: which sections exist, how they group in the
// navigation, and the keywords app search matches against. Extracted verbatim
// from src/pages/Settings.jsx.
import {
  Banknote,
  Bell,
  Clock,
  Gauge,
  Info,
  Monitor,
  Route,
  Shield,
  Smartphone,
  SlidersHorizontal,
  Target,
} from 'lucide-react';

export const SETTINGS_SECTIONS = [
  {
    id: 'settings-experience',
    group: 'app',
    title: 'App Experience',
    icon: SlidersHorizontal,
    detail: 'Switch between the coaching workspace and the advanced tracking console.',
    keywords: 'app experience mode coaching advanced tracking telemetry workspace switch',
    searchItems: [
      { label: 'App experience', targetLabel: 'App Experience', keywords: 'coaching mode advanced tracking mode workspace switch' },
    ],
  },
  {
    id: 'settings-tracking',
    group: 'driving-device',
    title: 'Tracking',
    icon: Shield,
    detail: 'Manual, auto-detect, background tracking, and pause controls.',
    keywords: 'manual auto detect background pause delayed start not starting drive signal gps movement',
    searchItems: [
      { label: 'Tracking mode', keywords: 'manual only auto detect background auto' },
      { label: 'Pause all tracking', keywords: 'stop disable trip detection' },
      { label: 'Auto-tracking', keywords: 'automatic start driving signals' },
      { label: 'Background tracking', keywords: 'record app closed location' },
    ],
  },
  {
    id: 'settings-android-permissions',
    group: 'driving-device',
    title: 'Android Permissions',
    icon: Shield,
    detail: 'Location, camera, activity, notification, battery, and native service setup.',
    keywords: 'location camera speed sign activity notification battery unrestricted native service usage bluetooth permission granted denied prompt',
    searchItems: [
      { label: 'Foreground location permission', targetLabel: 'Location', keywords: 'gps while using app' },
      { label: 'Background location permission', targetLabel: 'Background Location', keywords: 'always allow location' },
      { label: 'Camera permission', targetLabel: 'Camera', keywords: 'speed sign scanner offline ocr' },
      { label: 'Activity recognition permission', targetLabel: 'Physical Activity', keywords: 'physical activity driving detection' },
      { label: 'Notification permission', targetLabel: 'Notifications', keywords: 'alerts prompt' },
      { label: 'Battery optimization', keywords: 'unrestricted battery background service' },
      { label: 'Native auto-tracking service', targetLabel: 'Native Auto Tracking', keywords: 'android background automatic trips' },
    ],
  },
  {
    id: 'settings-feature-permissions',
    group: 'driving-device',
    title: 'Feature Permissions',
    icon: Info,
    detail: 'See which app features need setup before they can work.',
    keywords: 'blocked unavailable permission feature status camera speed sign scanner',
    searchItems: [
      { label: 'On-device speed-sign scanning', keywords: 'camera permission offline ocr mounted' },
      { label: 'Motion sensor access', keywords: 'accelerometer gyroscope crash detection' },
      { label: 'Phone Usage Access', keywords: 'distraction foreground app android' },
      { label: 'OBD-II Bluetooth diagnostics', keywords: 'nearby devices ble adapter' },
      { label: 'Road data and weather access', keywords: 'openstreetmap open meteo osrm network' },
      { label: 'Voice alerts', keywords: 'speech coaching text to speech' },
    ],
  },
  {
    id: 'settings-appearance',
    group: 'preferences',
    title: 'Appearance',
    icon: Monitor,
    detail: 'Theme, premium visuals, and unit preferences.',
    keywords: 'theme dark light system premium visuals units metric imperial kmh mph',
    searchItems: [
      { label: 'Theme', keywords: 'light dark system display' },
      { label: 'Premium Visual Experience', keywords: 'dashboard rich visuals totals cards' },
      { label: 'Units', keywords: 'metric imperial kmh mph kilometers miles' },
    ],
  },
  {
    id: 'settings-economics',
    group: 'preferences',
    title: 'Economics',
    icon: Banknote,
    detail: 'Currency, fuel, EV, carbon, and savings assumptions.',
    keywords: 'currency symbol money cost price co2 carbon emissions average vehicle baseline electric ev grid intensity kwh tree fuel savings economics',
    searchItems: [
      { label: 'Currency symbol', keywords: 'money cost dollar euro pound' },
      { label: 'Average vehicle CO2 baseline', keywords: 'emissions carbon comparison' },
      { label: 'Default EV efficiency', keywords: 'electric kwh per 100 km' },
      { label: 'Grid CO2 intensity', keywords: 'electricity emissions' },
      { label: 'Tree-year equivalent', keywords: 'carbon impact summary' },
    ],
  },
  {
    id: 'settings-notifications',
    group: 'preferences',
    title: 'Notifications',
    icon: Bell,
    detail: 'Quiet hours, trip summaries, coaching, maintenance, and safety alerts.',
    keywords: 'quiet hours trip summary coaching maintenance nudges alert',
    searchItems: [
      { label: 'Enable all notifications', keywords: 'master alerts toggle' },
      { label: 'Quiet hours', keywords: 'do not disturb start end time' },
      { label: 'Safety alerts', keywords: 'driving warning phone heading speeding danger zone' },
      { label: 'Trip started and ended notifications', keywords: 'start finish summary' },
      { label: 'Post-trip smart summary', keywords: 'score change phone use fuel saving' },
      { label: 'Coaching notifications', keywords: 'milestones achievements streak weekly driving summary tips' },
      { label: 'Maintenance reminders', keywords: 'vehicle service' },
      { label: 'No-trip nudge', keywords: 'inactive reminder days' },
    ],
  },
  {
    id: 'settings-driving-goals',
    group: 'coaching-detection',
    title: 'Driving Goals',
    icon: Target,
    detail: 'Weekly score, mileage, night driving, and behavior targets.',
    keywords: 'weekly score harsh brake speeding night goals target',
    searchItems: [
      { label: 'Maximum harsh brakes', keywords: 'weekly goal braking' },
      { label: 'Maximum speeding events', keywords: 'weekly goal speed' },
      { label: 'Minimum average score', keywords: 'weekly target' },
      { label: 'Maximum night distance and trips', keywords: 'night km driving goal' },
      { label: 'UBI annual mileage target', keywords: 'insurance mileage score' },
    ],
  },
  {
    id: 'settings-night-window',
    group: 'coaching-detection',
    title: 'Night Window',
    icon: Clock,
    detail: 'Night-trip detection window and sunset fallback.',
    keywords: 'night window sunset sunrise custom time late drive scoring',
    searchItems: [
      { label: 'Night driving start time', keywords: 'late evening begins' },
      { label: 'Night driving end time', keywords: 'morning ends' },
      { label: 'Sunset and sunrise fallback', keywords: 'automatic night window' },
    ],
  },
  {
    id: 'settings-detection-thresholds',
    group: 'coaching-detection',
    title: 'Detection Features',
    icon: SlidersHorizontal,
    detail: 'Detection toggles, sensitivity, calibration, and re-scoring.',
    keywords: 'harsh braking rapid acceleration speeding idle lane changing brake turn heading drift calibration rescore feedback accurate wrong false positive',
    searchItems: [
      { label: 'Detection feature switches', keywords: 'braking acceleration cornering speeding idle heading' },
      { label: 'Detection sensitivity', keywords: 'threshold strict lenient false positive' },
      { label: 'Calibration labels', keywords: 'feedback correct incorrect events' },
      { label: 'Re-score trip history', keywords: 'recalculate scoring version migration' },
      { label: 'Lane change and heading event scoring', keywords: 'advanced safety beta' },
    ],
  },
  {
    id: 'settings-advanced-models',
    group: 'coaching-detection',
    title: 'Advanced Models',
    icon: Route,
    detail: 'Sensor fusion, crash, route risk, voice alerts, OBD, and map overlays.',
    keywords: 'route risk voice alerts obd bluetooth sensor fusion crash map line event marker cornering heatmap',
    searchItems: [
      { label: 'Sensor fusion', keywords: 'motion accelerometer gyroscope gps' },
      { label: 'Crash detection', keywords: 'impact emergency safety' },
      { label: 'Emergency workflow', keywords: 'crash response' },
      { label: 'Predictive route risk', keywords: 'route warning hazard' },
      { label: 'Trip start voice confirmation', keywords: 'tracking started recording active spoken confirmation' },
      { label: 'Live voice alerts', keywords: 'spoken warning coaching safety test volume' },
      { label: 'OBD-II Bluetooth', keywords: 'vehicle adapter diagnostics ble' },
      { label: 'Map overlays', keywords: 'event markers heatmap route line' },
    ],
  },
  {
    id: 'settings-phone-use',
    group: 'coaching-detection',
    title: 'Phone Use Detection',
    icon: Smartphone,
    detail: 'Distraction detection, map display, scoring, and expert tuning.',
    keywords: 'distraction usage access phone score map foreground app',
    searchItems: [
      { label: 'Android Usage Access', keywords: 'permission foreground app' },
      { label: 'Phone use detection', keywords: 'distraction monitoring' },
      { label: 'Live phone use alert', keywords: 'driving warning notification' },
      { label: 'Show phone use on trip map', keywords: 'route markers' },
      { label: 'Include phone use in trip score', keywords: 'safety penalty' },
      { label: 'Phone detection expert tuning', keywords: 'threshold sensitivity duration' },
    ],
  },
  {
    id: 'settings-speed-warning',
    group: 'coaching-detection',
    title: 'Speed & Road Data',
    icon: Gauge,
    detail: 'Live speed checks, posted speed warnings, speed limits, weather, and automatic road-data lookup.',
    keywords: 'speed limits overpass osm warning margin over limit openstreetmap road data weather',
    searchItems: [
      { label: 'Live speed check', keywords: 'over limit alert coaching' },
      { label: 'On-device speed-sign scan', keywords: 'camera offline ocr mounted battery private notification auto start' },
      { label: 'Mounted Ready screen', keywords: 'arm next drive auto manual start camera visible foreground trip parked safety no touch awake timeout' },
      { label: 'Speed limits from OpenStreetMap', keywords: 'osm posted maxspeed' },
      { label: 'Fallback estimate country', keywords: 'canada united states global regional estimate' },
      { label: 'Weather from Open-Meteo', keywords: 'rain snow fog ice' },
      { label: 'Automatic road-data lookup', keywords: 'auto fetch speed weather' },
      { label: 'Snap route to roads with OSRM', keywords: 'map matching cleanup endpoint' },
      { label: 'OSRM timeout and endpoint', keywords: 'server route matching link' },
      { label: 'Speed check margin', keywords: 'strict lenient over limit kmh' },
    ],
  },
  {
    id: 'settings-privacy-data',
    group: 'privacy-data',
    title: 'Privacy & Data',
    icon: Shield,
    detail: 'Privacy zones, backups, exports, imports, deletion, and feedback data.',
    keywords: 'privacy export import backup retention delete data saved filters event feedback security',
    searchItems: [
      { label: 'Legal and privacy notice', targetLabel: 'Legal, safety, data & privacy notice', keywords: 'safety data external services' },
      { label: 'Privacy Intelligence', keywords: 'outbound records protections audit health' },
      { label: 'Request timing obfuscation', keywords: 'random delay network privacy' },
      { label: 'Decoy traffic', keywords: 'open meteo neutral location' },
      { label: 'App lock', keywords: 'fingerprint face device authentication' },
      { label: 'Screenshots and screen sharing', keywords: 'screen capture privacy' },
      { label: 'Privacy zones', keywords: 'home work hidden location radius map' },
      { label: 'Export all trips', keywords: 'csv download' },
      { label: 'Export everything', keywords: 'data portability json download' },
      { label: 'Export full backup', keywords: 'encrypted save password' },
      { label: 'Import backup', keywords: 'restore encrypted json' },
      { label: 'Erase all local data', keywords: 'delete erasure receipt local data' },
      { label: 'Data retention', keywords: 'delete trips days forever' },
      { label: 'Privacy log retention', keywords: 'operation records hours' },
      { label: 'Raw GPS retention', keywords: 'route coordinates delete days' },
      { label: 'Verify audit log', keywords: 'tamper chain integrity' },
      { label: 'Delete all trips', keywords: 'erase permanent danger' },
    ],
  },
];
